x-boot-node: &boot-node
  user: 'root'
  image: 'hyperledger/besu:latest'
  
services:

  boot-node-1:
    <<: *boot-node
    container_name: boot-node-1
    volumes:
      - ./config/besu/genesis.json:/opt/besu/conf/genesis.json
      - ./config/besu/config.toml:/opt/besu/conf/config.toml
      - ./config/besu:/opt/besu/conf
      - ./data/besu1:/opt/besu/data
    command:
      - --config-file=/opt/besu/conf/config.toml
      - --rpc-http-port=8541
      - --p2p-port=30301
    ports:
      - 8541:8541
      - 30301:30301
    networks:
      besu-net:
        ipv4_address: 172.28.0.2

  boot-node-2:
    <<: *boot-node
    container_name: boot-node-2
    volumes:
      - ./config/besu/genesis.json:/opt/besu/conf/genesis.json
      - ./config/besu/config.toml:/opt/besu/conf/config.toml
      - ./config/besu:/opt/besu/conf
      - ./data/besu2:/opt/besu/data
    command:
      - --config-file=/opt/besu/conf/config.toml
      - --rpc-http-port=8542
      - --p2p-port=30302
    ports:
      - 8542:8542
      - 30302:30302
    networks:
      besu-net:
        ipv4_address: 172.28.0.3

  boot-node-3:
    <<: *boot-node
    container_name: boot-node-3
    volumes:
      - ./config/besu/genesis.json:/opt/besu/conf/genesis.json
      - ./config/besu/config.toml:/opt/besu/conf/config.toml
      - ./config/besu:/opt/besu/conf
      - ./data/besu3:/opt/besu/data
    command:
      - --config-file=/opt/besu/conf/config.toml
      - --rpc-http-port=8543
      - --p2p-port=30303
    ports:
      - 8543:8543
      - 30303:30303
    networks:
      besu-net:
        ipv4_address: 172.28.0.4

  boot-node-4:
    <<: *boot-node
    container_name: boot-node-4
    volumes:
      - ./config/besu/genesis.json:/opt/besu/conf/genesis.json
      - ./config/besu/config.toml:/opt/besu/conf/config.toml
      - ./config/besu:/opt/besu/conf
      - ./data/besu4:/opt/besu/data
    command:
      - --config-file=/opt/besu/conf/config.toml
      - --rpc-http-port=8544
      - --p2p-port=30304
    ports:
      - 8544:8544
      - 30304:30304
    networks:
      besu-net:
        ipv4_address: 172.28.0.5

networks:
  besu-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/16